apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o2gc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o2gc
    app.kubernetes.io/part-of: veda-nodejs-sample
  name: devfile-sample-o2gc
  namespace: veda2019subs-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-o2gc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-o2gc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:3b8b857d601aa560d3b54d829c09512b28276a361be6be224762bb7ee15d6699
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
