apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o2gc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o2gc
    app.kubernetes.io/part-of: veda-nodejs-sample
  name: devfile-sample-o2gc
  namespace: veda2019subs-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-o2gc
status:
  loadBalancer: {}
